name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker Image
      run: docker-compose build
      env:
        GoogleDriveSettings__ClientId: ${{ secrets.CLIENT_ID }}
        GoogleDriveSettings__ClientSecret: ${{ secrets.CLIENT_SECRET }}
        UserTokensDatabaseSettings__ConnectionString: ${{ secrets.CONNECTION_STRING }}

    - name: Push the Docker Image
      run: docker-compose push

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy docker-compose File to Server
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "./docker-compose.yml"
          target: "/home/google-auth-redirect-app"
      
      - name: Pull Latest Image and Restart the Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            cd /home/oogle-auth-redirect-app
            docker-compose pull
            docker-compose up -d
